// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN_ywCFMla0wLErlewrjqlAFECQ4Kh_7A',
    appId: '1:61681064690:web:1d6a27243c73fc5dd6ce6b',
    messagingSenderId: '61681064690',
    projectId: 'superapp-4aec6',
    authDomain: 'superapp-4aec6.firebaseapp.com',
    storageBucket: 'superapp-4aec6.appspot.com',
    measurementId: 'G-F86NG35HWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CwElKWdd45BOYcs2WvapNpvGsI0aMuY',
    appId: '1:61681064690:android:8ae4da5995462075d6ce6b',
    messagingSenderId: '61681064690',
    projectId: 'superapp-4aec6',
    storageBucket: 'superapp-4aec6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAweDQYkVmSRfz3k5FsK8otB_XQPE6hOkQ',
    appId: '1:61681064690:ios:0687fb057206a427d6ce6b',
    messagingSenderId: '61681064690',
    projectId: 'superapp-4aec6',
    storageBucket: 'superapp-4aec6.appspot.com',
    androidClientId:
        '61681064690-aj0ss14grtvg3se0boc9ttkdnap43jcj.apps.googleusercontent.com',
    iosClientId:
        '61681064690-vcbhajcs34fiqmtkqnu1d5p188m30n98.apps.googleusercontent.com',
    iosBundleId: 'com.example.supperapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAweDQYkVmSRfz3k5FsK8otB_XQPE6hOkQ',
    appId: '1:61681064690:ios:0687fb057206a427d6ce6b',
    messagingSenderId: '61681064690',
    projectId: 'superapp-4aec6',
    storageBucket: 'superapp-4aec6.appspot.com',
    androidClientId:
        '61681064690-aj0ss14grtvg3se0boc9ttkdnap43jcj.apps.googleusercontent.com',
    iosClientId:
        '61681064690-vcbhajcs34fiqmtkqnu1d5p188m30n98.apps.googleusercontent.com',
    iosBundleId: 'com.example.supperapp',
  );
}
